<h1><strong>Random number generator</strong></h1>

Random numbers are extremely important in datascience , machine learning, simulations, sampling and testing algorithms.

Inside numpy library , we are having one module which is <code>random</code>

In [1]:
import numpy as np

<code>rand()</code>

In [3]:
np.random.rand()

0.9764856431623455

In [2]:
print(np.random.rand(5))

[0.91785624 0.54150732 0.27144366 0.84183452 0.73389117]


In [7]:
np.random.rand(2,3)

array([[0.61537674, 0.77934425, 0.65574482],
       [0.15357596, 0.98231738, 0.02360352]])

<code>randint()</code>

In [38]:
np.random.randint(1,7,(2,3))

array([[5, 6, 4],
       [4, 1, 2]])

<code>choice()</code>

In [74]:
np.random.choice([34,78,92,57,91,56],10)

array([91, 91, 78, 91, 91, 91, 92, 34, 78, 78])

In [83]:
np.random.choice([23,45,12,78],size=10,p=[0.1,0.2,0.3,0.4])

array([78, 78, 12, 78, 12, 78, 78, 78, 12, 23])

<code>shuffle()</code>

In [99]:
arr = np.array([1,2,4,5,6,7])
np.random.shuffle(arr)
print(arr)

[4 1 2 7 6 5]


<code>permutation()</code>

In [107]:
arr = np.array([1,2,3,4,5,6])
print(np.random.permutation(arr))
print(arr)

[3 4 2 6 5 1]
[1 2 3 4 5 6]


<h2 style="color:red;"><strong>seed()</strong></h2>

Sometimes we want same random numbers every time (for reproducibility)

In [141]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

<h3>Random numbers from <code>normal distribution</code></h3>

In [170]:
np.random.randn(3,3)

array([[-0.94305681,  1.40395874, -0.0185508 ],
       [-1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ]])

<h3>Generate normal distribution with <code>Mean and Std</code></h3>

In [180]:
np.random.normal(loc=50,scale=10,size=4)

array([75.39162716, 46.75509042, 47.94133283, 35.59958552])

<h3>Uniform Distribution</h3>

Generate numbers uniformly between two values.

In [183]:
np.random.uniform(low=10,high=20,size=5)

array([10.09197052, 11.01471543, 16.63501769, 10.05061584, 11.60808051])

<h3>Binomial Distribution</h3>

Used for success / failure experiments

In [266]:
np.random.binomial(n=10,p=0.999,size=5)

array([10, 10, 10, 10, 10])

<h3>Poisson Distribution</h3>

Used for even frequency

- Website visits
- Number of calls in call center
- Traffic flow

In [277]:
np.random.poisson(lam=5,size=6)

array([5, 6, 3, 4, 8, 4])

<h2>Generate one dataset</h2>

In [313]:
np.random.seed(42)

rating= np.random.rand(100)
income = np.random.randint(25000,88000,100)
age = np.random.randint(18,58,100)
target = np.random.randint(0,2,100)
city = np.random.choice(["mumbai","delhi","chandigarh","banglore","lucknow","noida"],100)

import pandas as pd

df = pd.DataFrame(rating,columns=['rating'])
df['age'] = age
df['city'] = city
df['income'] = income
df['target'] = target

df.head(10)

,rating,age,city,income,target
0,0.374540,36,banglore,73702,1
1,0.950714,19,chandigarh,75015,0
2,0.731994,43,banglore,76942,1
3,0.598658,49,delhi,81560,0
4,0.156019,23,delhi,66523,1
5,0.155995,49,noida,79268,0
6,0.058084,21,chandigarh,70151,1
7,0.866176,28,mumbai,47403,0
8,0.601115,34,delhi,43141,0
9,0.708073,55,noida,39820,1
