In [1]:
import numpy as np

Reverse numpy array

In [3]:
arr = np.array([2,3,1,6,8,4,0])
rev_arr = np.flip(arr)

print(rev_arr)

[0 4 8 6 1 3 2]


In [7]:
mat = np.array(
    [
        [2,7,5],
        [6,8,0],
        [2,5,4]
    ]
)

[[2,5,4],[6,8,0],[2,7,5]]

[[4,5,2],[0,8,6],[5,7,2]]

In [9]:
rev_mat = np.flip(mat,axis=1)
print(rev_mat)

[[5 7 2]
 [0 8 6]
 [4 5 2]]


In [14]:
flat_arr = mat.flatten()
flat_arr

array([2, 7, 5, 6, 8, 0, 2, 5, 4])

In [12]:
mat

array([[2, 7, 5],
       [6, 8, 0],
       [2, 5, 4]])

In [20]:
rv = mat.ravel()

flat_arr is mat

False

In [16]:
mat

array([[2, 7, 5],
       [6, 8, 0],
       [2, 5, 4]])

both flatten() and ravel() will give you the copy of flatten array


In [ ]:
help()

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [23]:
def double(a):
  '''Return a * 2'''
  return a * 2

In [24]:
double?

Signature: double(a)
Docstring: Return a * 2
File:      /var/folders/rh/6mrvv_4d71q__14h62_9f0c00000gn/T/ipykernel_67613/3639010673.py
Type:      function

<h2>Operations</h2>

In [25]:
ar = np.array([3,4,5,3,23])

Operation with scaler value

In [30]:
an = ar * 3
an = ar / 2
an = ar // 2
an = ar % 2
print(an)

[1 0 1 1 1]


In [31]:
mat = np.array(
    [
        [2,7,5],
        [6,8,0],
        [2,5,4]
    ]
)

In [32]:
print(mat*3)

[[ 6 21 15]
 [18 24  0]
 [ 6 15 12]]


In [34]:
ar1 = np.array([4,3,5])
ar2 = np.array([6,8,2])

print(ar1 + ar2)

[10 11  7]


Broadcasting

In [36]:
ar3 = [
    [3],
    [5],
    [6]
]

In [37]:
print(ar1 + ar3)

[[ 7  6  8]
 [ 9  8 10]
 [10  9 11]]


In [38]:
mat1 = np.array(
    [
    [3,4,2],
    [5,6,2],
    [5,6,2]
    ]
)

mat2 = np.array([
    [3,5,1],
    [5,7,2],
    [3,2,1]
])

In [39]:
mat1 * mat2

array([[ 9, 20,  2],
       [25, 42,  4],
       [15, 12,  2]])

In [41]:
mat3 = np.array(
    [
        [1,2,3],
        [2,1,1],
        [2,3,4]
    ]
)

mat4 = np.array(
    [
        [1,3,1],
        [3,2,2],
        [2,1,1]
    ]
)

In [42]:
mat3@mat4

array([[13, 10,  8],
       [ 7,  9,  5],
       [19, 16, 12]])