<h1><strong>Introduction to numpy</strong></h1>

NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures. 

https://numpy.org/doc/stable/user/absolute_beginners.html

In [4]:
[1,2,3,"jklsdf","jklsd",89.9,'a',[34,23,23]]

[1, 2, 3, 'jklsdf', 'jklsd', 89.9, 'a', [34, 23, 23]]

In [5]:
!pip install numpy

In [6]:
import numpy as np

<strong>1 D array</strong>

In [8]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [9]:
lst = [4,2,6,3,9,1]
ar = np.array(lst)
print(lst)
print(type(lst))
print(ar)
print(type(ar))

[4, 2, 6, 3, 9, 1]
<class 'list'>
[4 2 6 3 9 1]
<class 'numpy.ndarray'>


<strong>2 D Array </strong>

In [17]:
matrix = np.array(
    [[1,2],
     [4,5],
     [7,8]]
)

print(matrix)
print(type(matrix))

[[1 2]
 [4 5]
 [7 8]]
<class 'numpy.ndarray'>


<strong>3 D array</strong>

In [13]:
arr3D = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[0,9,8],[7,6,5],[4,3,2]],
    [[2,3,4],[5,6,7],[8,9,0]]
    ])

print(arr3D)
print(type(arr3D))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[0 9 8]
  [7 6 5]
  [4 3 2]]

 [[2 3 4]
  [5 6 7]
  [8 9 0]]]
<class 'numpy.ndarray'>


<h3><strong>Attributes of ndArray</strong></h3>

In [14]:
print(arr.ndim)
print(matrix.ndim)
print(arr3D.ndim)

1
2
3


In [18]:
print(arr.shape)
print(matrix.shape)
print(arr3D.shape)

(8,)
(3, 2)
(3, 3, 3)


In [19]:
print(arr.size)
print(matrix.size)
print(arr3D.size)

8
6
27


In [20]:
print(arr.dtype)

int64


<h2><strong>Creating basic arrays</strong></h2>

np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()


In [28]:
zeroArr = np.zeros((3,3,3))
print(zeroArr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [32]:
onesArr = np.ones((3,4,4))
print(onesArr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [41]:
emptyArr = np.empty((3,5,6))
print(emptyArr)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [ ]:
arangeArr = np.arange(1,6,2)
print(arangeArr)

[1 3 5]


In [45]:
linespaceArr = np.linspace(1,2,100)
print(linespaceArr)

[1.         1.01010101 1.02020202 1.03030303 1.04040404 1.05050505
 1.06060606 1.07070707 1.08080808 1.09090909 1.1010101  1.11111111
 1.12121212 1.13131313 1.14141414 1.15151515 1.16161616 1.17171717
 1.18181818 1.19191919 1.2020202  1.21212121 1.22222222 1.23232323
 1.24242424 1.25252525 1.26262626 1.27272727 1.28282828 1.29292929
 1.3030303  1.31313131 1.32323232 1.33333333 1.34343434 1.35353535
 1.36363636 1.37373737 1.38383838 1.39393939 1.4040404  1.41414141
 1.42424242 1.43434343 1.44444444 1.45454545 1.46464646 1.47474747
 1.48484848 1.49494949 1.50505051 1.51515152 1.52525253 1.53535354
 1.54545455 1.55555556 1.56565657 1.57575758 1.58585859 1.5959596
 1.60606061 1.61616162 1.62626263 1.63636364 1.64646465 1.65656566
 1.66666667 1.67676768 1.68686869 1.6969697  1.70707071 1.71717172
 1.72727273 1.73737374 1.74747475 1.75757576 1.76767677 1.77777778
 1.78787879 1.7979798  1.80808081 1.81818182 1.82828283 1.83838384
 1.84848485 1.85858586 1.86868687 1.87878788 1.88888889 1.89898